- name: OS | Install basic packages
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  with_items: "{{ packages }}"

- name: OS | Perform yum update
  yum:
    name: '*'
    state: latest
    update_cache: yes
  register: update_result

- name: HOST | Reboot server
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: update_result is changed
  
- name: HOST | Waiting server reboot
  wait_for_connection:
    connect_timeout: 60
    sleep: 5
    delay: 5
    timeout: 300
  when: update_result is changed

- name: HOST | Server ready
  debug:
    msg:
    - "Server is updated and restared with new kernel"
    - "Server ip {{ ansible_host }}"

